### ISSUE TITLE
앱 바 컴포넌트 생성 및 메뉴 구성

### ISSUE THREAD

**Issue by doheez** [MergeDoc/MergeDoc-frontend#4]
## Description
모든 페이지에서 보여지는 메뉴바를 생성한다. 메뉴바 좌측에 웹페이지의 대표 아이콘 및 로고 텍스트를 배치하고, `통합저장소`, `태그`, `병합하기` 메뉴를 로고 우측에 배치한다. 메뉴바를 반응형 컴포넌트로 구현하므로 언급한 메뉴들은 화면 너비가 900px 미만으로 줄어들 때 숨겨지며 메뉴 아이콘 클릭 시 나타난다.

메뉴바에서 사용자 프로필 아이콘을 최우측에 배치하고 아이콘 클릭 시 환경 설정 관련 메뉴들이 등장하도록 한다. 환경 설정 관련 메뉴들은 논의 전이므로 임시 텍스트를 사용한다.

## Todo
- [x] 대략적인 메뉴바 틀 생성
- [ ] 로고, 메뉴, 환경 설정 메뉴 등 세부 컴포넌트 추출
- [ ] 리덕스로 state 추출
- [ ] 메뉴바 색상 변경
- [ ] 새로운 폰트 논의 후 적용

## Reference
[1] https://mui.com/material-ui/api/app-bar/
